### ISSUE TITLE
User and auth views

### ISSUE THREAD

**Issue by rodrigodalcindev** [sprangular/sprangular#181]
Front-end work on these views need to be wrapped up as part of pull-request #63 .
- Sign In
 - [ ] Guest checkout column should only be displayed if non-authenticated users are coming via checkout CTA
 - [ ] Content of guest checkout column is misaligned within grid container
 - [ ] Missing copy on guest checkout button

- Account
 - [ ] Full front-end work needed
